User.create(email: "admin@gmail.com", password: "111111", role: 0, name: "admin")
User.create(email: "asad@gmail.com", password: "111111", role: 0, name: "asad")
CurrencyRate.create(rate: 12000.00, finished_at: nil)
ProductCategory.create(name: "Прочие")
Provider.create(name: "Клиент", weight: 1)
Buyer.create(name: "Клиент", weight: 1)
Storage.create(name: "склад 1")
Storage.create(name: "склад 2")
